import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import GlobalState from './context';
import Navbar from './component/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <GlobalState>
          <Navbar />
          <main className='min-h-screen flex flex-col mt-20'>{children}</main>
        </GlobalState>
      </body>
    </html>
  );
}
